### ISSUE TITLE
tadaam

### ISSUE THREAD

**Issue by anna02test** [CommitethTesters/nov11#1]

**Comment by status-open-bounty** [comment]
Balance: 0.012000 ETH
Tokens: SNT: 22.00
Contract address: [0x6d4b612be2c677d24ae92a5b91a2b97c327011d7](https://ropsten.etherscan.io/address/0x6d4b612be2c677d24ae92a5b91a2b97c327011d7)
Network: Testnet (Ropsten)
Status: Pending maintainer confirmation
Winner: annadanchenko
